spring.application.name=Optimizacion

server.port=8082

spring.datasource.url=jdbc:postgresql://ep-billowing-union-aqhino3v.c-8.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_cL5P0jiZMlnQ&sslmode=require&channelBinding=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_cL5P0jiZMlnQ

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect